In [4]:
class demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
print(p1.fact(5))

120


In [5]:
class Demo2:
     
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [7]:
# some inheritance
# parent class
class person():
    #constructor
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isEmployee(self):
        return False
# derived class
class Employee(person):
    def isEmployee(self):
        return True
    
    

emp=person("Anil")
print(emp.getname(),emp.isEmployee())

emp1=employee("Akhil")
print(emp.getname(),emp.isEmployee())


Anil False


NameError: name 'employee' is not defined

In [8]:
list=[1,2,3,4]
print(list)

[1, 2, 3, 4]


In [12]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
print(array)

[1 2 3 4]


In [10]:
list=[1,2,3,4]
array=np.array(list)
print(array.shape)
print(array.dtype)


(4,)
int32


In [13]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [17]:
a1=np.array([(1,2,3),(4,5,6)])
print('row and column',a1[1:,])

row and column [[4 5 6]]


In [18]:
a1=np.array([(1,2,3),(4,5,6)])
print('first row',a1[0])

first row [1 2 3]


In [19]:
a1=np.array([(1,2,3),(4,5,6)])
print('second row',a1[1])

second row [4 5 6]


In [21]:
a1=np.random.normal(5,1,10)
print(a1)
print('min value',np.min(a1))
print('min value',np.max(a1))
print('min value',np.mean(a1))
print('min value',np.median(a1))

[4.37756397 3.67206902 6.11071189 6.11254312 5.96571879 3.72604512
 4.57973645 3.89702398 5.05220446 5.51682184]
min value 3.6720690216368417
min value 6.112543116976031
min value 4.90104386305466
min value 4.815970457176466


In [22]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [23]:
c1=np.array([1,2])
c2=np.array([(4,5),(1,2)])
np.dot(c1,c2)

array([6, 9])